# Bind semua interface agar ESP di LAN bisa connect (bukan hanya 127.0.0.1)
listener 1883 0.0.0.0
allow_anonymous false
password_file mosquitto.passwd
persistence false
connection_messages true
log_type error
log_type warning
log_type notice
log_type information
